sudo: required
services:
  - docker

language: generic

before_install:
  - docker build -t sherryyu/udemy-docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true sherryyu/udemy-docker-react npm run test